package com.opotapov.stonks

import com.opotapov.network.Stock
import com.opotapov.network.YFQuoteResponse
import com.opotapov.network.YFQuoteResultResponse
import kotlinx.serialization.decodeFromString
import kotlinx.serialization.json.Json
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue

class CommonGreetingTest {

    @Test
    fun testExample() {
        assertTrue(Greeting().greeting().contains("Hello"), "Check 'Hello' is mentioned")
    }

    @Test
    fun testStonksSerialization() {
        val content = """
            {
    "quoteResponse": {
        "result": [
            {
                "language": "en-US",
                "region": "US",
                "quoteType": "EQUITY",
                "typeDisp": "Equity",
                "quoteSourceName": "Nasdaq Real Time Price",
                "triggerable": true,
                "customPriceAlertConfidence": "HIGH",
                "currency": "USD",
                "exchange": "NMS",
                "shortName": "Apple Inc.",
                "longName": "Apple Inc.",
                "messageBoardId": "finmb_24937",
                "exchangeTimezoneName": "America/New_York",
                "exchangeTimezoneShortName": "EST",
                "gmtOffSetMilliseconds": -18000000,
                "market": "us_market",
                "esgPopulated": false,
                "marketState": "REGULAR",
                "forwardPE": 24.67732,
                "priceToBook": 36.830986,
                "sourceInterval": 15,
                "exchangeDataDelayedBy": 0,
                "pageViewGrowthWeekly": -0.19498384,
                "averageAnalystRating": "1.8 - Buy",
                "tradeable": false,
                "fullExchangeName": "NasdaqGS",
                "financialCurrency": "USD",
                "regularMarketOpen": 161.475,
                "averageDailyVolume3Month": 97273930,
                "averageDailyVolume10Day": 92899110,
                "fiftyTwoWeekLowChange": 43.270004,
                "fiftyTwoWeekLowChangePercent": 0.36404178,
                "fiftyTwoWeekRange": "118.86 - 182.94",
                "fiftyTwoWeekHighChange": -20.809998,
                "fiftyTwoWeekHighChangePercent": -0.113753125,
                "fiftyTwoWeekLow": 118.86,
                "fiftyTwoWeekHigh": 182.94,
                "dividendDate": 1644451200,
                "earningsTimestamp": 1643301000,
                "earningsTimestampStart": 1651003200,
                "earningsTimestampEnd": 1651521600,
                "trailingAnnualDividendRate": 0.865,
                "trailingPE": 26.954283,
                "trailingAnnualDividendYield": 0.0054941564,
                "epsTrailingTwelveMonths": 6.015,
                "epsForward": 6.57,
                "epsCurrentYear": 6.16,
                "priceEpsCurrentYear": 26.319807,
                "sharesOutstanding": 16319399936,
                "bookValue": 4.402,
                "fiftyDayAverage": 170.2702,
                "fiftyDayAverageChange": -8.140198,
                "fiftyDayAverageChangePercent": -0.04780753,
                "twoHundredDayAverage": 152.9718,
                "twoHundredDayAverageChange": 9.158203,
                "twoHundredDayAverageChangePercent": 0.05986857,
                "marketCap": 2645864480768,
                "firstTradeDateMilliseconds": 345479400000,
                "priceHint": 2,
                "regularMarketChange": 4.6900024,
                "regularMarketChangePercent": 2.978914,
                "regularMarketTime": 1646849402,
                "regularMarketPrice": 162.13,
                "regularMarketDayHigh": 162.69,
                "regularMarketDayRange": "159.41 - 162.69",
                "regularMarketDayLow": 159.41,
                "regularMarketVolume": 47667305,
                "regularMarketPreviousClose": 157.44,
                "bid": 162.55,
                "ask": 161.92,
                "bidSize": 9,
                "askSize": 10,
                "displayName": "Apple",
                "symbol": "AAPL"
            },
            {
                "language": "en-US",
                "region": "US",
                "quoteType": "EQUITY",
                "typeDisp": "Equity",
                "quoteSourceName": "Nasdaq Real Time Price",
                "triggerable": true,
                "customPriceAlertConfidence": "HIGH",
                "currency": "USD",
                "exchange": "NMS",
                "shortName": "Netflix, Inc.",
                "longName": "Netflix, Inc.",
                "messageBoardId": "finmb_32012",
                "exchangeTimezoneName": "America/New_York",
                "exchangeTimezoneShortName": "EST",
                "gmtOffSetMilliseconds": -18000000,
                "market": "us_market",
                "esgPopulated": false,
                "marketState": "REGULAR",
                "forwardPE": 25.067503,
                "priceToBook": 10.090478,
                "sourceInterval": 15,
                "exchangeDataDelayedBy": 0,
                "pageViewGrowthWeekly": 0.042010006,
                "averageAnalystRating": "2.3 - Buy",
                "tradeable": false,
                "fullExchangeName": "NasdaqGS",
                "financialCurrency": "USD",
                "regularMarketOpen": 357.685,
                "averageDailyVolume3Month": 7720884,
                "averageDailyVolume10Day": 5400610,
                "fiftyTwoWeekLowChange": 10.019989,
                "fiftyTwoWeekLowChangePercent": 0.028612189,
                "fiftyTwoWeekRange": "350.2 - 700.99",
                "fiftyTwoWeekHighChange": -340.77,
                "fiftyTwoWeekHighChangePercent": -0.48612675,
                "fiftyTwoWeekLow": 350.2,
                "fiftyTwoWeekHigh": 700.99,
                "earningsTimestamp": 1642694400,
                "earningsTimestampStart": 1650312000,
                "earningsTimestampEnd": 1650657600,
                "trailingAnnualDividendRate": 0.0,
                "trailingPE": 32.048042,
                "trailingAnnualDividendYield": 0.0,
                "epsTrailingTwelveMonths": 11.24,
                "epsForward": 14.37,
                "epsCurrentYear": 11.0,
                "priceEpsCurrentYear": 32.747272,
                "sharesOutstanding": 443963008,
                "bookValue": 35.699,
                "fiftyDayAverage": 457.7026,
                "fiftyDayAverageChange": -97.482605,
                "fiftyDayAverageChangePercent": -0.21298242,
                "twoHundredDayAverage": 547.087,
                "twoHundredDayAverageChange": -186.86697,
                "twoHundredDayAverageChangePercent": -0.34156722,
                "marketCap": 159924355072,
                "firstTradeDateMilliseconds": 1022160600000,
                "priceHint": 2,
                "regularMarketChange": 18.459991,
                "regularMarketChangePercent": 5.4014487,
                "regularMarketTime": 1646849395,
                "regularMarketPrice": 360.22,
                "regularMarketDayHigh": 364.14,
                "regularMarketDayRange": "350.5089 - 364.14",
                "regularMarketDayLow": 350.5089,
                "regularMarketVolume": 3892182,
                "regularMarketPreviousClose": 341.76,
                "bid": 361.65,
                "ask": 361.83,
                "bidSize": 12,
                "askSize": 11,
                "displayName": "Netflix",
                "symbol": "NFLX"
            }, 
            {
                "language": "en-US",
                "region": "US",
                "quoteType": "EQUITY",
                "typeDisp": "Equity",
                "quoteSourceName": "Nasdaq Real Time Price",
                "triggerable": true,
                "customPriceAlertConfidence": "HIGH",
                "currency": "USD",
                "firstTradeDateMilliseconds": -110197800000,
                "priceHint": 2,
                "regularMarketChange": -0.019989014,
                "regularMarketChangePercent": -0.008972133,
                "regularMarketTime": 1646849530,
                "regularMarketPrice": 222.77,
                "regularMarketDayHigh": 227.19,
                "regularMarketDayRange": "222.0866 - 227.19",
                "regularMarketDayLow": 222.0866,
                "regularMarketVolume": 2467474,
                "regularMarketPreviousClose": 222.79,
                "bid": 223.25,
                "ask": 223.37,
                "bidSize": 8,
                "askSize": 8,
                "fullExchangeName": "NYSE",
                "financialCurrency": "USD",
                "regularMarketOpen": 226.79,
                "averageDailyVolume3Month": 3085025,
                "averageDailyVolume10Day": 4399630,
                "fiftyTwoWeekLowChange": 14.529999,
                "fiftyTwoWeekLowChangePercent": 0.06977525,
                "fiftyTwoWeekRange": "208.24 - 271.15",
                "fiftyTwoWeekHighChange": -48.37999,
                "fiftyTwoWeekHighChangePercent": -0.1784252,
                "fiftyTwoWeekLow": 208.24,
                "fiftyTwoWeekHigh": 271.15,
                "dividendDate": 1647302400,
                "earningsTimestamp": 1643266810,
                "earningsTimestampStart": 1651062600,
                "earningsTimestampEnd": 1651494600,
                "trailingAnnualDividendRate": 5.25,
                "trailingPE": 22.188248,
                "trailingAnnualDividendYield": 0.023564793,
                "epsTrailingTwelveMonths": 10.04,
                "epsForward": 11.1,
                "epsCurrentYear": 10.13,
                "priceEpsCurrentYear": 21.991116,
                "sharesOutstanding": 743585024,
                "bookValue": -6.177,
                "fiftyDayAverage": 256.0798,
                "fiftyDayAverageChange": -33.3098,
                "fiftyDayAverageChangePercent": -0.13007586,
                "twoHundredDayAverage": 245.8021,
                "twoHundredDayAverageChange": -23.03209,
                "twoHundredDayAverageChangePercent": -0.093701765,
                "marketCap": 165648433152,
                "forwardPE": 20.069368,
                "priceToBook": -36.064434,
                "sourceInterval": 15,
                "exchangeDataDelayedBy": 0,
                "pageViewGrowthWeekly": 0.35218292,
                "averageAnalystRating": "2.0 - Buy",
                "tradeable": false,
                "marketState": "REGULAR",
                "exchange": "NYQ",
                "shortName": "McDonald's Corporation",
                "longName": "McDonald's Corporation",
                "messageBoardId": "finmb_139488",
                "exchangeTimezoneName": "America/New_York",
                "exchangeTimezoneShortName": "EST",
                "gmtOffSetMilliseconds": -18000000,
                "market": "us_market",
                "esgPopulated": false,
                "displayName": "McDonald's",
                "symbol": "MCD"
            }
        ],
        "error": null
    }
}
        """
        val actualStonks = Json {
            ignoreUnknownKeys = true
        }.decodeFromString<YFQuoteResponse>(content)
        val expectedStonks = YFQuoteResponse(YFQuoteResultResponse(listOf(
            Stock(161.92, "Apple", "AAPL"),
            Stock(361.83, "Netflix", "NFLX"),
            Stock(223.37, "McDonald's", "MCD")
        )))
        assertEquals(expectedStonks, actualStonks)
    }
}